language: cpp
dist: xenial
compiler: clang
env:
  LSLDIST_URL="https://github.com/sccn/liblsl/releases/download"
  UBUNTU_DIST="xenial"
  LSL_VERSION="1.13.0-b4"
  OSXVER=MacOS10.13
  - CMakeArgs=""
matrix:
  include:
#  - os: linux
#    addons:
#      apt:
#        packages:
#        - qt5-default
#    before_script:
#    - travis_retry wget ${LSLDIST_URL}/liblsl-${LSL_VERSION}-Linux64-${UBUNTU_DIST}.deb
#    - dpkg -x *.deb LSL
#    - export LSL_INSTALL_ROOT=LSL/usr
#    - export CMakeArgs="-DLSL_UNIXFOLDERS=1 ${CMakeArgs}"
  - os: osx
    osx_image: xcode10.1
    before_script:
    - travis_retry wget ${LSLDIST_URL}/${LSL_VERSION}/liblsl-${LSL_VERSION}-${OSXVER}.tar.bz2
    - mkdir LSL; tar -xf *.tar.bz2 -C LSL
    - export LSL_INSTALL_ROOT=LSL
    - brew install qt 
    - export CMAKE_PREFIX_PATH=/usr/local/opt/qt/
script:
- mkdir -p build/install
- cd build
- cmake --version
- cmake -DLSL_INSTALL_ROOT=${LSL_INSTALL_ROOT} $CMakeArgs ../
- cmake --build . --config Release --target install
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then for app in *.app; do ${CMAKE_PREFIX_PATH}/bin/macdeployqt ${app} -dmg; mv "${app%.app}.dmg" "${app%.app}-${LSL_VERSION}-OSX64.dmg}"; done; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpack; fi
- cd ..
